name: Generate Data

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install Dependencies (Python)
        run: |
          python -m pip install --upgrade pip
          pip install pypinyin requests tqdm
      - name: Build
        run: python main.py
      - name: Deploy to GitHub Pages
        if: ${{ github.event_name == 'push' && github.repository_owner == 'oierdb-ng' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          user_name: BaoshuoBot
          user_email: bot@baoshuo.ren
          cname: oier-data.baoshuo.dev

  sync:
    if: ${{ github.event_name == 'push' && github.repository_owner == 'oierdb-ng' }}
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: gh-pages
      - name: Checkout renbaoshuo/cdn-sb
        uses: actions/checkout@v3
        with:
          repository: renbaoshuo/cdn-sb
          ssh-key: ${{ secrets.CDN_SB_SSH_PRIVATE_KEY }}
          path: cdn-sb
      - name: Rename Files
        run: |
          STATIC_SHA512=$(jq -r .sha512 static.sha512.json)
          RESULT_SHA512=$(jq -r .sha512 result.sha512.json)

          echo static.json $STATIC_SHA512
          echo result.txt $RESULT_SHA512

          rm -rf cdn-sb/public/oier
          mkdir -p cdn-sb/public/oier
          cp static.json cdn-sb/public/oier/static.${STATIC_SHA512:0:7}.json
          cp result.txt cdn-sb/public/oier/result.${RESULT_SHA512:0:7}.txt
      - id: get-commit-sha
        run: |
          id="${{ github.sha }}"
          echo "::set-output name=id::${id:0:7}"
      - name: Upload
        run: |
          cd cdn-sb
          git config --global user.name BaoshuoBot
          git config --global user.email bot@baoshuo.dev
          git add public/oier
          git commit -m "[OIerDb/${{ steps.get-commit-sha.outputs.id }}] Upload dist on $(date '+%Y-%m-%d %H:%M:%S')" --allow-empty
          git push
